### ISSUE TITLE
when I used CommandProcess 

### ISSUE THREAD

**Issue by amirtaherkhani** [justengel/continuous_threading#1]
An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by justengel** [comment]
This error is for the multiprocessing library. Before you run the main portion of your script you need to call `multiprocessing.freeze_support()`.  https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support
