### ISSUE TITLE
How to trigger a cleanup function on thread termination

### ISSUE THREAD

**Issue by brendan-simon-indt** [justengel/continuous_threading#3]
I see that `ContinuousThread` has hooks for Thread initialisation (`init=` in args) and also for the thread main loop (`target=` in args).

Is there a way to specify a cleanup function when a thread terminates?  e.g. to write out stuff from queue to disk, etc?

I there a standard function of override?

**Comment by justengel** [comment]
The `stop` and `close` methods were made for this purpose. In general with threads the `join` method is supposed to clean up the thread. All of these functions run in the main thread and not the thread itself like `init`.

I thought you had a good idea, so I added a cleanup function in version 2.0.6.

**Comment by brendan-simon-indt** [comment]
Ok, thanks.  I guess it's an alternative way of cleaning up threads.  It might help to not forget to call the cleanup functions manually, if specifying the cleanup function at thread instantiation time 🤷‍♂️

**Comment by brendan-simon-indt** [comment]
I found a gotcha that someone else might experience so thought I'd mention it :)

I had a thread subclass derived from `ContinuousThread` and it had `cleanup()` methods.  These stopped working due to the `cleanup` attribute withing the `ContinuousThread` being set to `None`.

I need to rename my cleanup methods or use the `cleanup` hooks.
